/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdme_plugins_webpulseforecast_WebPulseForecastNative */

#ifndef _Included_com_gdme_plugins_webpulseforecast_WebPulseForecastNative
#define _Included_com_gdme_plugins_webpulseforecast_WebPulseForecastNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdme_plugins_webpulseforecast_WebPulseForecastNative
 * Method:    analyzeProjectType
 * Signature: (Ljava/lang/String;)Lcom/gdme/webpulseforecast/WebPulseForecastNative/ProjectType;
 */
JNIEXPORT jobject JNICALL Java_com_gdme_webpulseforecast_WebPulseForecastNative_analyzeProjectType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gdme_plugins_webpulseforecast_WebPulseForecastNative
 * Method:    estimateResources
 * Signature: (Lcom/gdme/plugins/webpulseforecast/WebPulseForecastNative/ProjectType;)Lcom/gdme/plugins/webpulseforecast/WebPulseForecastNative/ResourceEstimation;
 */
JNIEXPORT jobject JNICALL Java_com_gdme_webpulseforecast_WebPulseForecastNative_estimateResources
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_gdme_plugins_webpulseforecast_WebPulseForecastNative
 * Method:    calculatePerformanceImpact
 * Signature: (Lcom/gdme/plugins/webpulseforecast/WebPulseForecastNative/ProjectType;)D
 */
JNIEXPORT jdouble JNICALL Java_com_gdme_webpulseforecast_WebPulseForecastNative_calculatePerformanceImpact
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_gdme_plugins_webpulseforecast_WebPulseForecastNative
 * Method:    getResourceUsageDisplay
 * Signature: (Lcom/gdme/plugins/webpulseforecast/WebPulseForecastNative/ResourceEstimation;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gdme_webpulseforecast_WebPulseForecastNative_getResourceUsageDisplay
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_gdme_plugins_webpulseforecast_WebPulseForecastNative
 * Method:    getPotentialIssues
 * Signature: (Lcom/gdme/plugins/webpulseforecast/WebPulseForecastNative/ProjectType;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_gdme_webpulseforecast_WebPulseForecastNative_getPotentialIssues
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
